<?php

/**
 * JobeetCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Farrukh Umurzakov
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class JobeetCategory extends BaseJobeetCategory
{
    public function countActiveJobs()
    {
        $q = Doctrine_Query::create()
            ->from('JobeetJob j')
            ->where('j.category_id = ?', $this->getId());

        return Doctrine_Core::getTable('JobeetJob')->countActiveJobs($q);
    }
    public function getSlug()
    {
        return Jobeet::slugify($this->getName());
    }
}