<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/10/22 22:48:29
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 20,
));
